jenkins-docker/jobs/Create new Jenkins Server/config.xml
jenkins-docker/jobs/Destroy Old Jenkins Server/config.xml

jenkins access to existing security group

---

jenkins-docker/jobs/Check For Updates/config.xml
jenkins-docker/jobs/Import_and_Rekey_HPDS_Data/config.xml
jenkins-docker/jobs/Update Bucket Policy/config.xml

updating jenkin jobs to perform new rekey process and remove concepts from the columnMeta.javabin

Adding updated jenkins jobs

---

jenkins-docker/jobs/Docker-AWSCLI/config.xml

update for Docker-awscli job.  Now able to create new amis based on centos 7 CIS's current version

Update to awscli ami creation

---

jenkins-docker/jobs/Teardown and Rebuild Stage Environment/config.xml

Updating to Teardown job and adding a Jenkins global property

Updating teardown job

---

.gitignore
jenkins-docker/Dockerfile
jenkins-docker/hudson.tasks.Maven.xml
jenkins-docker/jobs/PIC-SURE Auth Micro-App Build/config.xml
jenkins-docker/jobs/PIC-SURE-API Build/config.xml
jenkins-docker/jobs/PIC-SURE-HPDS Build/config.xml
jenkins-docker/jobs/PIC-SURE-HPDS-DICTIONARY Build/config.xml
jenkins-docker/jobs/PIC-SURE-HPDS-DICTIONARY-RESOURCE Build/config.xml
jenkins-docker/jobs/PIC-SURE-HPDS-UI Docker Build/config.xml
jenkins-docker/jobs/PIC-SURE-VISUALIZATION Build/config.xml
jenkins-docker/jobs/Update PIC-SURE Token Introspection Token/config.xml

ALS-4780: Update jenkins to use maven installed by apt-get into permanent directory

---

jenkins-docker/jobs/Teardown and Rebuild Stage Environment/config.xml

[ALS-4998] Adjust configurable infrastructure to support both Auth and Open HPDS instances simultaneously.

[ALS-4998] Add new env vars to terraform

---

jenkins-docker/jobs/biodatacatalyst-ui/config.xml

[ALS 4796] Modify Jenkins for Open Access

[ALS 4796] Modify Jenkins for Open Access

---

jenkins-docker/jobs/biodatacatalyst-ui/config.xml

Update Biodatacatalyst UI Job to handle Open Access

Update Biodatacatalyst UI Job to handle Open Access

---

jenkins-docker/jobs/Teardown and Rebuild Stage Environment/config.xml
jenkins-docker/jobs/biodatacatalyst-ui/config.xml

[ALS-5134] Google Tag Manager

---

jenkins-docker/jobs/PIC-SURE Open Build/config.xml
jenkins-docker/jobs/PIC-SURE Pipeline/config.xml
jenkins-docker/jobs/biodatacatalyst-ui/config.xml

[ALS-5164] Allow Tags for Open BDC frontend in release control

[ALS-5164] Allow Tags for Open BDC frontend in release control

---

jenkins-docker/Dockerfile
jenkins-docker/jobs/Bash_Functions/config.xml
jenkins-docker/jobs/Deployment Pipeline/config.xml
jenkins-docker/jobs/Import HPDS VCF Data/config.xml
jenkins-docker/jobs/Import_and_Rekey_HPDS_Data/config.xml
jenkins-docker/jobs/PIC-SURE Open Build/config.xml
jenkins-docker/jobs/PIC-SURE Pipeline/config.xml
jenkins-docker/jobs/Rollback Jenkins State/config.xml
jenkins-docker/jobs/Teardown and Rebuild Stage Environment/config.xml
jenkins-docker/jobs/biodatacatalyst-ui/config.xml
jenkins-docker/plugins.txt

* Organizing and Cleaning up Jenkins dockerfile
* Added Role Strategy Plugin
* Syncing Jobs

[ALS-5279] - Adding Role Strategy Plugin

---

jenkins-docker/jobs/Terraform Destroy Stack - Standalone/config.xml

[ALS-5344] Banner config now uploads to S3

[ALS-5344] Banner config now uploads to S3

---

jenkins-docker/config.xml
jenkins-docker/jobs/Morning Jobs/config.xml
jenkins-docker/jobs/Nightly Jobs/config.xml
jenkins-docker/jobs/Terraform Destroy Stack - Standalone/config.xml

[ALS-5549] Update Standalone teardown and rebuild job

[ALS-5549] Update Standalone teardown and rebuild job

---

jenkins-docker/jobs/Bash_Functions/config.xml
jenkins-docker/jobs/Create Database Snapshot/config.xml
jenkins-docker/jobs/Create Top Admin/config.xml
jenkins-docker/jobs/Database Migrations/config.xml
jenkins-docker/jobs/Delete Databases - Testing/config.xml
jenkins-docker/jobs/Deployment Pipeline/config.xml
jenkins-docker/jobs/Export Builds/config.xml
jenkins-docker/jobs/Morning Jobs/config.xml
jenkins-docker/jobs/Teardown and Rebuild Stage Environment/config.xml
jenkins-docker/jobs/Update PIC-SURE Token Introspection Token/config.xml

- Removed `do_picsure_rds_strategy` as we only have one implemented strategy at a time. We will now be using the persisted database.
- RDS Snapshots functions 
- `create_snapshot_when_available` will wait for the RDS instance to become available and then create a snapshot.
- `get_latest_snapshot_identifier` retrieves the most recent snapshot identifier for a specified RDS instance.
- `manage_rds_snapshots` can be used to keep only the latest 3 manually created RDS snapshots and delete the rest
- JWT Tokens Functions
- `get_jwt_expiration_date` Extract and return the expiration date of the JWT token
- `is_expiring_soon` Check if the token is expiring within the next 30 days
- Secret Functions
- `fetch_secret` fetch a secret from the AWS secrets manager
- `extract_field` Uses `jq` to …

[ALS-5082] Persist database

---

jenkins-docker/jobs/Teardown and Rebuild Stage Environment/config.xml

[ALS-6225] PIC-SURE will use RDS 7 day rotating password

[ALS-6225] PIC-SURE will use RDS 7 day rotating password

---

jenkins-docker/jobs/Import HPDS VCF Data/config.xml

* Needs to be a groovy system script.
* Should be a declarative pipeline.

[ALS - 6004] - Needs to be Groovy System Script

---

jenkins-docker/jobs/Morning Jobs/config.xml
jenkins-docker/jobs/Nightly Jobs/config.xml

This will deploy at 6am (7am during daylight savings) and shutdown at 7pm (8pm during daylight savings)

Update the job schedules to be reasonable in eastern time

---

jenkins-docker/Dockerfile
jenkins-docker/jobs/Database PSQL - Dictionary Import dump and pg_restore/config.xml

* s3 location of the dump comes from RC build-spec.json defined by source_dictionary_db_s3_url
* Extract and organize dump files. 
* Test connection 
* Run pg_restore

[ALS-7318] - Adding data import using pg_restore

---

jenkins-docker/Dockerfile
jenkins-docker/config.xml
jenkins-docker/groovy_library/README.md
jenkins-docker/groovy_library/vars/AWSHelper.groovy
jenkins-docker/jobs/Database PSQL - Dictionary Import dump and pg_restore/config.xml
jenkins-docker/jobs/Deploy Dictionary in place/config.xml
jenkins-docker/jobs/Deploy Dictionary to Existing WildFly EC2/config.xml
jenkins-docker/jobs/Deploy Frontend to Existing Httpd EC2/config.xml
jenkins-docker/jobs/Deploy New UI in place/config.xml
jenkins-docker/jobs/Dictionary - Container Build with DB Build Args/jenkinsfile
jenkins-docker/jobs/Dictionary - Container Build/jenkinsfile
jenkins-docker/jobs/Dictionary - Weights CSV File/jenkinsfile
jenkins-docker/jobs/Download PIC-SURE-Frontend Configuration/config.xml
jenkins-docker/jobs/Download picsure-dictionary Configuration/config.xml
jenkins-docker/jobs/PIC-SURE Dictionary - Jenkinsfile/config.xml
jenkins-docker/jobs/PIC-SURE Dictionary - Jenkinsfile/jenkinsfile
jenkins-docker/jobs/PIC-SURE Dictionary Weights - Jenkinsfile/config.xml
jenkins-docker/jobs/PIC-SURE Dictionary Weights - Jenkinsfile/jenkinsfile
jenkins-docker/jobs/PIC-SURE Frontend Build/config.xml
jenkins-docker/jobs/PIC-SURE Pipeline/config.xml
jenkins-docker/jobs/Teardown and Rebuild Stage Environment/config.xml
jenkins-docker/jobs/Upload PIC-SURE-Frontend Configuration/config.xml
jenkins-docker/jobs/Upload picsure-dictionary Configuration/config.xml

Merge release and release-new-ui

Merge release and release-new-ui

---

jenkins-docker/jobs/PIC-SURE-HPDS Build/config.xml

Update HPDS Build

---

jenkins-docker/jobs/Bash_Functions/config.xml

Added the ':Z' flag to the Docker volume mount for SELinux compatibility.

Update Docker volume flag
